### ISSUE TITLE
mlmodel file missing

### ISSUE THREAD

**Issue by cruinh** [tomwildcat9/ImageDetector#1]
Hi!  Maybe you're just not allowed to redistribute it yourself, or maybe you just have a bad link in the project file...  but if it's the latter, the Resnet50.mlmodel isn't included the repo.  Not a huge deal since it's available from Apple too, but thought I'd mention it anyway.  Thanks for sharing this demo :)

**Comment by cruinh** [comment]
oh my bad.  the file's there.  the reference in the Xcode project file is just not pointing to it.

**Comment by AirZona** [comment]
Hey Matt! Hope you are doing well!

huh, I just tried cloning this repo on my MacBook, this project has only been on my iMac and it works fine. A few times when I was working with another project with a Core ML model it lost reference too. I think it is an Xcode 9 issue.

**Comment by cruinh** [comment]
Yeah I think you're right.  Looks like there might be an Xcode bug.  I tried re-adding the file on my mac here, and it looks like it got the file path wrong.  When I drag the file over to Xcode and check "Copy files if needed", it looks like it doesn't actually do the copy.  It just creates a reference to the original file.

**Comment by AirZona** [comment]
Yea, I am sure the next beta or two they will fix it. hopefully, lol.
